set_property IOSTANDARD LVTTL [get_ports {AD[13]}]
set_property IOSTANDARD LVTTL [get_ports {AD[12]}]
set_property IOSTANDARD LVTTL [get_ports {AD[11]}]
set_property IOSTANDARD LVTTL [get_ports {AD[10]}]
set_property IOSTANDARD LVTTL [get_ports {AD[9]}]
set_property IOSTANDARD LVTTL [get_ports {AD[8]}]
set_property IOSTANDARD LVTTL [get_ports {AD[7]}]
set_property IOSTANDARD LVTTL [get_ports {AD[6]}]
set_property IOSTANDARD LVTTL [get_ports {AD[5]}]
set_property IOSTANDARD LVTTL [get_ports {AD[4]}]
set_property IOSTANDARD LVTTL [get_ports {AD[3]}]
set_property IOSTANDARD LVTTL [get_ports {AD[2]}]
set_property IOSTANDARD LVTTL [get_ports {AD[1]}]
set_property IOSTANDARD LVTTL [get_ports {AD[0]}]
set_property IOSTANDARD LVTTL [get_ports ad_clk]
set_property IOSTANDARD LVTTL [get_ports clk]
set_property IOSTANDARD LVTTL [get_ports DRY]
set_property IOSTANDARD LVTTL [get_ports ovr_in]
set_property IOSTANDARD LVTTL [get_ports rx_ready]
set_property IOSTANDARD LVTTL [get_ports tx]
set_property IOSTANDARD LVTTL [get_ports tx_ready]
set_property PACKAGE_PIN F3 [get_ports ad_clk]
set_property PACKAGE_PIN F4 [get_ports DRY]
set_property PACKAGE_PIN M4 [get_ports ovr_in]
set_property PACKAGE_PIN A7 [get_ports rx_ready]
set_property PACKAGE_PIN B6 [get_ports tx]
set_property PACKAGE_PIN B7 [get_ports tx_ready]
set_property PACKAGE_PIN L4 [get_ports {AD[0]}]
set_property PACKAGE_PIN K3 [get_ports {AD[1]}]
set_property PACKAGE_PIN J3 [get_ports {AD[2]}]
set_property PACKAGE_PIN H3 [get_ports {AD[3]}]
set_property PACKAGE_PIN H4 [get_ports {AD[4]}]
set_property PACKAGE_PIN H5 [get_ports {AD[5]}]
set_property PACKAGE_PIN L2 [get_ports {AD[6]}]
set_property PACKAGE_PIN L3 [get_ports {AD[7]}]
set_property PACKAGE_PIN J1 [get_ports {AD[8]}]
set_property PACKAGE_PIN K1 [get_ports {AD[9]}]
set_property PACKAGE_PIN H1 [get_ports {AD[10]}]
set_property PACKAGE_PIN H2 [get_ports {AD[11]}]
set_property PACKAGE_PIN G1 [get_ports {AD[12]}]
set_property PACKAGE_PIN G2 [get_ports {AD[13]}]
set_property PACKAGE_PIN N11 [get_ports clk]

connect_debug_port u_ila_0/probe0 [get_nets [list {AD_inst1/ad_reg2[0]} {AD_inst1/ad_reg2[1]} {AD_inst1/ad_reg2[2]} {AD_inst1/ad_reg2[3]} {AD_inst1/ad_reg2[4]} {AD_inst1/ad_reg2[5]} {AD_inst1/ad_reg2[6]} {AD_inst1/ad_reg2[7]} {AD_inst1/ad_reg2[8]} {AD_inst1/ad_reg2[9]} {AD_inst1/ad_reg2[10]} {AD_inst1/ad_reg2[11]} {AD_inst1/ad_reg2[12]} {AD_inst1/ad_reg2[13]}]]
connect_debug_port dbg_hub/clk [get_nets ad_clk_OBUF]


set_property MARK_DEBUG true [get_nets clk_100]
connect_debug_port u_ila_0/probe1 [get_nets [list clk_100]]
connect_debug_port dbg_hub/clk [get_nets clk_100]


set_property MARK_DEBUG true [get_nets PLL_inst0/clk_out1]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list PLL_inst0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {data_out_re[0]} {data_out_re[1]} {data_out_re[2]} {data_out_re[3]} {data_out_re[4]} {data_out_re[5]} {data_out_re[6]} {data_out_re[7]} {data_out_re[8]} {data_out_re[9]} {data_out_re[10]} {data_out_re[11]} {data_out_re[12]} {data_out_re[13]} {data_out_re[14]} {data_out_re[15]} {data_out_re[16]} {data_out_re[17]} {data_out_re[18]} {data_out_re[19]} {data_out_re[20]} {data_out_re[21]} {data_out_re[22]} {data_out_re[23]} {data_out_re[24]} {data_out_re[25]} {data_out_re[26]} {data_out_re[27]} {data_out_re[28]} {data_out_re[29]} {data_out_re[30]} {data_out_re[31]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list PLL_inst0/inst/clkfbout_buf_PLL]]
set_property PROBE_TYPE TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list PLL_inst0/inst/clk_out1_PLL]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 14 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {AD_IBUF[0]} {AD_IBUF[1]} {AD_IBUF[2]} {AD_IBUF[3]} {AD_IBUF[4]} {AD_IBUF[5]} {AD_IBUF[6]} {AD_IBUF[7]} {AD_IBUF[8]} {AD_IBUF[9]} {AD_IBUF[10]} {AD_IBUF[11]} {AD_IBUF[12]} {AD_IBUF[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 14 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {s_axis_data_tdata[0]} {s_axis_data_tdata[1]} {s_axis_data_tdata[2]} {s_axis_data_tdata[3]} {s_axis_data_tdata[4]} {s_axis_data_tdata[5]} {s_axis_data_tdata[6]} {s_axis_data_tdata[7]} {s_axis_data_tdata[8]} {s_axis_data_tdata[9]} {s_axis_data_tdata[10]} {s_axis_data_tdata[11]} {s_axis_data_tdata[12]} {s_axis_data_tdata[13]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clkfbout_buf_PLL]
