set_property IOSTANDARD LVTTL [get_ports {AD[13]}]
set_property IOSTANDARD LVTTL [get_ports {AD[12]}]
set_property IOSTANDARD LVTTL [get_ports {AD[11]}]
set_property IOSTANDARD LVTTL [get_ports {AD[10]}]
set_property IOSTANDARD LVTTL [get_ports {AD[9]}]
set_property IOSTANDARD LVTTL [get_ports {AD[8]}]
set_property IOSTANDARD LVTTL [get_ports {AD[7]}]
set_property IOSTANDARD LVTTL [get_ports {AD[6]}]
set_property IOSTANDARD LVTTL [get_ports {AD[5]}]
set_property IOSTANDARD LVTTL [get_ports {AD[4]}]
set_property IOSTANDARD LVTTL [get_ports {AD[3]}]
set_property IOSTANDARD LVTTL [get_ports {AD[2]}]
set_property IOSTANDARD LVTTL [get_ports {AD[1]}]
set_property IOSTANDARD LVTTL [get_ports {AD[0]}]
set_property IOSTANDARD LVTTL [get_ports ad_clk]
set_property IOSTANDARD LVTTL [get_ports clk]
set_property IOSTANDARD LVTTL [get_ports DRY]
set_property IOSTANDARD LVTTL [get_ports ovr_in]
set_property IOSTANDARD LVTTL [get_ports rx_ready]
set_property IOSTANDARD LVTTL [get_ports tx]
set_property IOSTANDARD LVTTL [get_ports tx_ready]
set_property PACKAGE_PIN F3 [get_ports ad_clk]
set_property PACKAGE_PIN F4 [get_ports DRY]
set_property PACKAGE_PIN M4 [get_ports ovr_in]
set_property PACKAGE_PIN A7 [get_ports rx_ready]
set_property PACKAGE_PIN B6 [get_ports tx]
set_property PACKAGE_PIN B7 [get_ports tx_ready]
set_property PACKAGE_PIN L4 [get_ports {AD[0]}]
set_property PACKAGE_PIN K3 [get_ports {AD[1]}]
set_property PACKAGE_PIN J3 [get_ports {AD[2]}]
set_property PACKAGE_PIN H3 [get_ports {AD[3]}]
set_property PACKAGE_PIN H4 [get_ports {AD[4]}]
set_property PACKAGE_PIN H5 [get_ports {AD[5]}]
set_property PACKAGE_PIN L2 [get_ports {AD[6]}]
set_property PACKAGE_PIN L3 [get_ports {AD[7]}]
set_property PACKAGE_PIN J1 [get_ports {AD[8]}]
set_property PACKAGE_PIN K1 [get_ports {AD[9]}]
set_property PACKAGE_PIN H1 [get_ports {AD[10]}]
set_property PACKAGE_PIN H2 [get_ports {AD[11]}]
set_property PACKAGE_PIN G1 [get_ports {AD[12]}]
set_property PACKAGE_PIN G2 [get_ports {AD[13]}]
set_property PACKAGE_PIN N11 [get_ports clk]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list PLL_inst0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 14 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {AD_inst1/ad_reg2[0]} {AD_inst1/ad_reg2[1]} {AD_inst1/ad_reg2[2]} {AD_inst1/ad_reg2[3]} {AD_inst1/ad_reg2[4]} {AD_inst1/ad_reg2[5]} {AD_inst1/ad_reg2[6]} {AD_inst1/ad_reg2[7]} {AD_inst1/ad_reg2[8]} {AD_inst1/ad_reg2[9]} {AD_inst1/ad_reg2[10]} {AD_inst1/ad_reg2[11]} {AD_inst1/ad_reg2[12]} {AD_inst1/ad_reg2[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 28 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {FIFO_Control_inst3/data_uart[0]} {FIFO_Control_inst3/data_uart[1]} {FIFO_Control_inst3/data_uart[2]} {FIFO_Control_inst3/data_uart[4]} {FIFO_Control_inst3/data_uart[5]} {FIFO_Control_inst3/data_uart[6]} {FIFO_Control_inst3/data_uart[7]} {FIFO_Control_inst3/data_uart[8]} {FIFO_Control_inst3/data_uart[9]} {FIFO_Control_inst3/data_uart[10]} {FIFO_Control_inst3/data_uart[12]} {FIFO_Control_inst3/data_uart[13]} {FIFO_Control_inst3/data_uart[14]} {FIFO_Control_inst3/data_uart[15]} {FIFO_Control_inst3/data_uart[16]} {FIFO_Control_inst3/data_uart[17]} {FIFO_Control_inst3/data_uart[18]} {FIFO_Control_inst3/data_uart[20]} {FIFO_Control_inst3/data_uart[21]} {FIFO_Control_inst3/data_uart[22]} {FIFO_Control_inst3/data_uart[23]} {FIFO_Control_inst3/data_uart[24]} {FIFO_Control_inst3/data_uart[25]} {FIFO_Control_inst3/data_uart[26]} {FIFO_Control_inst3/data_uart[28]} {FIFO_Control_inst3/data_uart[29]} {FIFO_Control_inst3/data_uart[30]} {FIFO_Control_inst3/data_uart[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets ad_clk_OBUF]
