# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TOP.xdc

# IP: E:/Workspace/Vivado_16.4/2017_11_5_FFT/Design/IP_Core/ROM/ROM/ROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM || ORIG_REF_NAME==ROM}]
